import { defineField, defineType } from "sanity";

const localized = (name: string, title: string, group: string, long = false) =>
  defineField({
    name,
    title,
    type: long ? "localizedText" : "localizedString",
    group,
  });

export const siteSettings = defineType({
  name: "siteSettings",
  title: "홈페이지 문구",
  type: "document",
  groups: [
    { name: "navigation", title: "메뉴" },
    { name: "intro", title: "01 Intro" },
    { name: "daily", title: "이전 하루 데이터" },
    { name: "products", title: "02 Product" },
    { name: "life", title: "이전 삶 데이터" },
    { name: "contact", title: "엔딩/연락처" },
    { name: "metadata", title: "검색/공유" },
  ],
  fields: [
    defineField({
      name: "pageLabels",
      title: "화면 이름",
      type: "object",
      group: "navigation",
      fields: [
        defineField({ name: "intro", title: "Intro", type: "localizedString" }),
        defineField({ name: "product", title: "Product", type: "localizedString" }),
        defineField({ name: "contact", title: "Contact", type: "localizedString" }),
      ],
    }),
    defineField({
      name: "navigation",
      title: "상단 메뉴",
      type: "object",
      group: "navigation",
      fields: [
        defineField({ name: "daily", title: "하루", type: "localizedString" }),
        defineField({ name: "products", title: "제품", type: "localizedString" }),
        defineField({ name: "life", title: "삶", type: "localizedString" }),
      ],
    }),
    defineField({
      name: "language",
      title: "언어 버튼",
      type: "object",
      group: "navigation",
      fields: [
        defineField({ name: "korean", title: "한국어 버튼", type: "string" }),
        defineField({ name: "english", title: "영어 버튼", type: "string" }),
      ],
    }),
    defineField({
      name: "introScenes",
      title: "Intro 장면",
      type: "array",
      group: "intro",
      of: [{ type: "introScene" }],
    }),
    localized("dailyEyebrow", "챕터 이름", "daily"),
    localized("dailyTitle", "첫 화면 제목", "daily", true),
    localized("dailyBody", "첫 화면 설명", "daily", true),
    localized("dailyCta", "스크롤 버튼", "daily"),
    localized("dailyJourneyLabel", "하루 장면 안내", "daily"),
    defineField({
      name: "dailyScenes",
      title: "하루 장면",
      type: "array",
      group: "daily",
      of: [{ type: "dailyScene" }],
    }),
    localized("dailyClosingTitle", "하루 엔딩 제목", "daily", true),
    localized("dailyClosingBody", "하루 엔딩 설명", "daily", true),
    localized("productsEyebrow", "챕터 이름", "products"),
    localized("productsTitle", "제품 제목", "products", true),
    localized("productsBody", "제품 설명", "products", true),
    localized("productsTransitionTitle", "logu 등장 제목", "products", true),
    localized("productsTransitionBody", "logu 등장 설명", "products", true),
    localized("productsComingSoon", "출시 예정 문구", "products"),
    localized("productsVisit", "제품 이동 문구", "products"),
    localized("productsGuide", "제품 안내 문구", "products", true),
    localized("productsLead", "제품 한 줄 강조", "products"),
    localized("productsSupport", "제품 보조 문구", "products", true),
    localized("lifeEyebrow", "챕터 이름", "life"),
    localized("lifeTitle", "삶 제목", "life", true),
    localized("lifeBody", "삶 설명", "life", true),
    defineField({
      name: "lifeStages",
      title: "삶의 장면",
      type: "array",
      group: "life",
      of: [{ type: "lifeStage" }],
    }),
    localized("lifeClosingTitle", "삶 엔딩 제목", "life", true),
    localized("lifeClosingBody", "삶 엔딩 설명", "life", true),
    localized("contactEyebrow", "엔딩 챕터 이름", "contact"),
    localized("contactLabel", "Contact 표시 이름", "contact"),
    localized("contactTitle", "연락처 제목", "contact", true),
    localized("contactBody", "연락처 설명", "contact", true),
    defineField({ name: "contactEmail", title: "이메일", type: "string", group: "contact", validation: (rule) => rule.email() }),
    localized("contactLocation", "위치 문구", "contact"),
    localized("copyright", "저작권 문구", "contact"),
    localized("metaTitle", "사이트 제목", "metadata"),
    localized("metaDescription", "사이트 설명", "metadata", true),
    defineField({
      name: "hero",
      title: "이전 Hero 데이터",
      type: "object",
      hidden: true,
      fields: [
        defineField({ name: "tagline", title: "Tagline", type: "string" }),
        defineField({ name: "subline", title: "Subline", type: "string" }),
      ],
    }),
    defineField({ name: "philosophy", title: "이전 Philosophy 데이터", type: "text", hidden: true }),
    defineField({ name: "studio", title: "이전 Studio 데이터", type: "text", hidden: true }),
    defineField({
      name: "contact",
      title: "이전 Contact 데이터",
      type: "object",
      hidden: true,
      fields: [
        defineField({ name: "headline", title: "Headline", type: "string" }),
        defineField({ name: "email", title: "Email", type: "string" }),
      ],
    }),
  ],
  preview: { prepare: () => ({ title: "홈페이지 전체 문구 · 한국어/English" }) },
});
