const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'public/films/apps-2026-10-06'),manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json'),'utf8'));
(async()=>{assert.equal(manifest.length,15);const b=await chromium.launch({headless:true,executablePath:'C:/Users/jkhon/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'}),report=[],errors=[];
 try{for(const width of [1440,393]){const p=await b.newPage({viewport:{width,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8780/films/apps-2026-10-06/index.html');await p.waitForFunction(()=>document.querySelectorAll('video').length===15);assert.equal(await p.locator('.app').count(),3);assert.equal(await p.locator('a[download$="mp4"]').count(),15);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.close()}
 const p=await b.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8780/films/apps-2026-10-06/index.html');
 for(const m of manifest){const r=await p.evaluate(async m=>{const v=Array.from(document.querySelectorAll('video')).find(v=>v.src.endsWith('/'+m.file));v.muted=true;v.preload='auto';v.load();await new Promise((ok,no)=>{v.addEventListener('loadedmetadata',ok,{once:true});v.addEventListener('error',()=>no(Error(v.error?.message)),{once:true});setTimeout(()=>no(Error('metadata timeout')),15000)});const metrics={duration:v.duration,width:v.videoWidth,height:v.videoHeight};v.currentTime=m.duration/2;await new Promise((ok,no)=>{v.addEventListener('seeked',ok,{once:true});setTimeout(()=>no(Error('seek timeout')),15000)});await v.play();const start=v.currentTime;await new Promise(r=>setTimeout(r,350));metrics.played=v.currentTime>start;metrics.error=v.error?.code||0;v.pause();return metrics},m);assert.ok(Math.abs(r.duration-m.duration)<.1);assert.equal(r.width,m.width);assert.equal(r.height,m.height);assert.equal(r.played,true);assert.equal(r.error,0);report.push({key:m.key,...r});console.log('PLAY '+m.key)}
 const siteChecks=[];
 if(process.env.FILM_SITE_URL){for(const width of [1440,393]){const site=await b.newPage({viewport:{width,height:900}});site.on('pageerror',e=>errors.push(e.message));for(const app of ['memogrip','goodgo','bookbap']){assert.equal((await site.goto(process.env.FILM_SITE_URL+'/apps/'+app+'?lang=ko')).status(),200);assert.equal(await site.locator('.film-video-options button').count(),3);assert.equal(await site.locator('video').count(),0);assert.ok(await site.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await site.locator('button.film-player-poster').click();await site.waitForFunction(()=>document.querySelector('video')?.readyState>=1);const video=await site.locator('video').evaluate(v=>{v.pause();return {src:v.currentSrc,duration:v.duration}});assert.ok(video.src.endsWith(app+'-intro.mp4'));assert.ok(Math.abs(video.duration-20)<.1);siteChecks.push({app,width,...video})}await site.close()}}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'artifacts/app-films-2026-10-06/browser-report.json'),JSON.stringify({galleryViewports:[1440,393],errors,clips:report,siteChecks},null,2));
 }finally{await b.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
