// Read-only deployment verification. No form submissions or CMS mutations.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),base=process.env.FILM_PUBLIC_URL||'https://logusstudio.com',manifest=JSON.parse(fs.readFileSync(path.join(root,'public/films/apps-2026-10-06/manifest.json'),'utf8'));
(async()=>{const results=[];const request=async(route,status=200,options={})=>{const response=await fetch(base+route,{redirect:'manual',signal:AbortSignal.timeout(30000),...options});assert.equal(response.status,status,route+' '+response.status);results.push({route,status:response.status});return response};
 for(const route of ['/','/apps','/apps/bebe?lang=ko','/apps/bebe?lang=en']){const html=await(await request(route)).text();assert.ok(html.includes('DayByBaby'),route);if(route==='/')assert.ok(html.includes('id="contact"'))}
 for(const app of ['memogrip','goodgo','bookbap']){const html=await(await request('/apps/'+app+'?lang=ko')).text();const imagePath=html.replace(/%2F/gi,'/');assert.ok(imagePath.includes('/films/apps-2026-10-06/'+app+'-intro-poster.jpg'));assert.ok(html.includes('film-video-options'));assert.ok(html.includes(app+'-vertical-guide.mp4'));console.log('DETAIL '+app)}
 const json=await(await request('/films/apps-2026-10-06/manifest.json')).json();assert.equal(json.length,15);
 for(const clip of manifest){const route='/films/apps-2026-10-06/'+clip.file,r=await request(route,206,{headers:{Range:'bytes=0-1023'}});assert.equal(r.headers.get('content-range'),'bytes 0-1023/'+clip.bytes);assert.ok(r.headers.get('content-type')?.includes('video/mp4'));const remote=Buffer.from(await r.arrayBuffer()),fd=fs.openSync(path.join(root,'public/films/apps-2026-10-06/'+clip.file),'r'),local=Buffer.alloc(1024);try{fs.readSync(fd,local,0,1024,0)}finally{fs.closeSync(fd)}assert.deepEqual(remote,local);await request('/films/apps-2026-10-06/'+clip.poster,200,{method:'HEAD'});await request('/films/apps-2026-10-06/'+clip.key+'.srt',200,{method:'HEAD'});console.log('MEDIA '+clip.key)}
 await request('/films/apps-2026-10-06/index.html');await request('/apps-art/daybybaby-app-icon.png',200,{method:'HEAD'});await request('/opengraph-image',200,{method:'HEAD'});
 for(const route of ['/manage','/manage/operations']){const r=await request(route,307);assert.ok(r.headers.get('location')?.includes('/manage/login'))}
 await request('/api/manage/releases/fixture/download',401);
 const dir=path.join(root,'artifacts/app-films-2026-10-06');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'published-report.json'),JSON.stringify({base,checkedAt:new Date().toISOString(),pass:true,results},null,2));console.log('Published pages, 15 byte-matched Range videos, posters, captions, OG and admin protection PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
